function Fsym = force(in1,s,alpha,mu,beta,gama,Le)
%FORCE
%    FSYM = FORCE(IN1,S,ALPHA,MU,BETA,GAMA,LE)

%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    12-Oct-2013 20:12:44

a1 = in1(:,1);
a2 = in1(:,2);
a3 = in1(:,3);
a4 = in1(:,4);
a5 = in1(:,5);
a6 = in1(:,6);
t2 = s.^2;
t3 = t2.^2;
t4 = t3.*1.5e1;
t5 = s.*t3.*3.0;
t6 = Le.^2;
t7 = s.*t2.*1.0e1;
t8 = s.*t3.*6.0;
t9 = -t4+t7+t8;
t10 = a4.*t9;
t11 = s.*t2.*4.0;
t19 = t3.*7.0;
t12 = t11-t19+t5;
t13 = t3.*3.0;
t14 = s.*t3;
t15 = t3.*8.0;
t22 = s.*t2.*6.0;
t16 = s+t15-t22-t5;
t17 = Le.*a2.*t16;
t18 = a1.*(t4-t7-t8+1.0);
t27 = s.*t2.*3.0;
t20 = t13-t14+t2-t27;
t21 = a3.*t20.*t6.*(1.0./2.0);
t28 = t3.*2.0;
t23 = -t28+s.*t2+s.*t3;
t24 = a6.*t23.*t6.*(1.0./2.0);
t26 = Le.*a5.*t12;
t25 = t10+t17+t18+t21+t24-t26;
t29 = 1.0./t25.^2;
t30 = beta.*t29;
t31 = 1.0./t25.^3;
t32 = mu.*t31;
t33 = 1.0./t25;
t34 = beta.*gama.*t33;
t35 = 1.0./t25.^4;
t36 = alpha.*t35;
t37 = t30+t32+t34+t36;
Fsym = [(t4-t7-t8+1.0).*(t30+t32+t34+alpha.*1.0./(t10+t17+a1.*(t4-s.*t2.*1.0e1-s.*t3.*6.0+1.0)+a3.*t6.*(t13+t2-s.*t2.*3.0-s.*t3).*(1.0./2.0)+a6.*t6.*(t14-t3.*2.0+s.*t2).*(1.0./2.0)-Le.*a5.*t12).^4);Le.*t16.*t37;t20.*t37.*t6.*(1.0./2.0);t37.*t9;-Le.*t12.*t37;t23.*t37.*t6.*(1.0./2.0)];
